#HopeCommander - v 1.2
#This configuration can be ignored. This is only important for servers who would wan't to use sudo commands on players

#If a player should be able to execute that command with the required permissions below it (default: false)
allowPlayersCommandUsage: false

#The Permission for the function above | unaffected then "allowPlayersCommandUsage" is false (default: hopecommander.useCommand)
PermissionNode: hopecommander.useCommand

#Should it also be executable by Operators (some Plugins may not have a way to set specific Permissions,
#but can give the Player some kind of "Temporary Operator Status" | unaffected then "allowPlayersCommandUsage" is false (default: false)


#When enabled
#If player has op but not permission=execute
#If player has no op but permission=execute

#When disabled
#If player has op but not permission=dont execute
#If player has no op but permission=execute
allowOperatorExecution: false