#Spigot related
name: HopeCommander-Spigot
main: me.hopedev.hopecommander.Spigot.SpigotMain
version: 1.0.0
api-version: 1.14
description: A Bridge between spigot and bungee, one way only
commands:
  hc:
    description: Main Command for HopeCommander
    permission: hc.command